# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(c560bf1a-4936-44df-a105-9a4cb9b0d217)'
    appType: 'webApp'
    WebAppName: 'anzarpipeline'
    deployToSlotOrASE: true
    ResourceGroupName: 'testpipelinerg'
    SlotName: 
    packageForLinux: 'dist/tal-web-app/'
